version: "3.2"

services:
  backend:
    container_name: dbproj-backend
    image: node:10-alpine
    volumes:
      - .:/server
    command: sh -c 'cd /server && yarn && yarn start:dev'
    ports:
      - 3001:3000
    environment:
      MYSQL_URL:

